<?php

namespace AppBundle\Repository;

/**
 * SwimmingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwimmingRepository extends \Doctrine\ORM\EntityRepository
{
}
