<?php

namespace AppBundle\Repository;

/**
 * SwimingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SwimingRepository extends \Doctrine\ORM\EntityRepository
{
}
