<?php

namespace AppBundle\Repository;

/**
 * WalkingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalkingRepository extends \Doctrine\ORM\EntityRepository
{
    public function sortByDistanceAndStep()
    {

    }

}
